receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/jaeger:
    endpoint: "http://jaeger:4318"  # Jaeger OTLP HTTP port
    tls:
      insecure: true

  debug: {}   # console logging

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]