global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus kendi metrikleri
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Node Exporter metrikleri
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MSSQL Exporter metrikleri
  - job_name: 'mssql'
    static_configs:
      - targets: ['mssql-exporter:9182']

  # PostgreSQL Exporter metrikleri
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter metrikleri
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules.yml